### ISSUE TITLE
Question: Total Fatalities

### ISSUE THREAD

**Issue by gregorybleiker** [openZH/covid_19#1216]
I don't understand the number "Total Fatalities" on the overview page:
![image](https://user-images.githubusercontent.com/1917329/96679700-74b3b300-1374-11eb-8d7a-d710906b41e9.png)

Does this not indicate that 194 people have died since 1.6. from covid-19? According to the accumulated number in the sources (and other numbers published) for instance ncumul_deceased for GE alone is at 321.

**Comment by naspert** [comment]
csv files from this repo have data from beginning of March (roughly). So GE has 321 deceased from this date. The site corona-data.ch did its 'count reset' internally.

**Comment by metaodi** [comment]
I can't speak for corona-data.ch, since this repository is only providing data.

But from a quick glance the number looks alright. The ncumul_deceased of 321 from GE is referring to cumulative number of deceased since the beginning of the pandemic. So in GE ncumul_deceased was 294 on 1.6.2020, so since then 321 - 294 = 27 people died in GE.

Hope this helps.
