### ISSUE TITLE
TG shows 0 cases on map (but there are 1002, currently)

### ISSUE THREAD

**Issue by bittner** [openZH/covid_19#1297]
Does the scraping / parsing of data work for canton Thurgau TG?

[The map](https://www.corona-data.ch/) shows 0 (zero) cases, but we personally know of several ones for roughly a week. Also, the following sources show numbers way beyond 0:

- [Fachdossier Coronavirus](https://www.tg.ch/news/fachstab-gesundheit-coronavirus.html/10552) (tg.ch)
- [Fallzahlen Kanton Thurgau](https://opendata.swiss/de/dataset/covid_19-fallzahlen-kanton-thurgau/resource/49c1fdc7-6380-43d9-a0dd-f1b3a85f96a2) (opendata.swiss)

**Comment by metaodi** [comment]
@bittner the `0` on the map refers to "Newly reported cases" and actally (according to TG) there were no new cases since yesterday. Here is the [relevant part of our CSV](https://github.com/openZH/covid_19/blob/master/fallzahlen_kanton_total_csv_v2/COVID19_Fallzahlen_Kanton_TG_total.csv#L240-L241):

![Screenshot_20201030-195101](https://user-images.githubusercontent.com/538415/97745581-60488680-1ae9-11eb-8ee4-baf445c7ace6.png)

It's possible, that at a later date this number changes ("Nachmeldungen").
