### ISSUE TITLE
Ticino definition of "intubate"

### ISSUE THREAD

**Issue by pedrodude** [openZH/covid_19#215]
The manual updates for Ticino seem to have become slightly confused with number of people "intubated" being either recorded in ncumul_ICU_intub or in ncumul_vent.

The situation updates from Ticino provide numbers of "pazienti... di cui N intubate".  In my understanding as a native English speaker (who does not have medical knowledge), intubation is distinct from ventilation.  However, I'm not sure if this is also the case in Italian, or whether the canton does indeed mean patients who are on a ventilator.

C'è qualcuno chi è una madrelingua italiana o parla fluentemente, che può chiarire la definizione precisa di "intubate" in questo contesto?

In either case, the recorded data are inconsistent.

**Comment by tlorusso** [comment]
Related to #153. Thx for the hint. Looking into it, might be a problem in the case of other cantons as well. ZH says 'werden künstlich beatmet', not sure if this means intubated OR ventilated (or one of the two?).

**Comment by andreasamsler** [comment]
@GD-ZH please clarify, what ZH means with 'werden künstlich beatmet', (a) ventilated or (b) intubated. Thanks. Best, Andreas

**Comment by tlorusso** [comment]
I've just received confirmation that 'intubato' really just refers to intubated cases in TI. Closes #215

**Comment by pedrodude** [comment]
> I've just received confirmation that 'intubato' really just refers to intubated cases in TI. This needs to be corrected in the data.

Interesting, why is that figure important to report?

**Comment by baryluk** [comment]
Yes, I would also want to know also, as I am finishing the new scraper for TI to report this data as part of https://github.com/openZH/covid_19/issues/257

**Comment by baryluk** [comment]
My limited medical understanding is that technically (or rather semantically ) intubated and ventilated refer to different things, but AFAIK everyone that needs to be (mechanical) ventilated needs to be intubated, and almost every one that is intubated, is because they are connected to mechanical ventilator. The two terms refer to different parts of the same thing. Intubation itself is the process of inserting and securing the tube, and the face of having the tube. There few possible ways one can get the tube, but usually it is through natural canal and mouth. The mechanical ventilation, is the fact and ongoing process of this tube used with a machine that provides artificial breathing of means of external positive and negative pressure.

I don't know the details, but it does make sense to me.

Technically patient could be intubated, and not (mechanical) ventilated, but it would be either short, or during emergency situation (like in the field, or during sudden problems), where it could be ventilated by hand.

So to me intubated == ventilated (+/- 1).

**Comment by tlorusso** [comment]
Related to #260

**Comment by baryluk** [comment]
I was wrong in my comment at https://github.com/openZH/covid_19/issues/215#issuecomment-605374256  . It is possible to be ventilated, without intubation. And it is quite common. Sorry.

**Comment by pedrodude** [comment]
It'd be good to know from someone in the TI government (and any other cantons that have similar ambiguity around wording) what this means as it presumably affects the use of this stat as a proxy variable.
I'd guess that the interpretation of "number of people requiring external breathing assistance" (which apparently doesn't necessarily need to be done by machine) helps clarify the severity of the illness, while "number of people connected to a mechanical breathing machines" would help clarify the risk of resource exhaustion.  But for the moment I don't think we can assume either.

**Comment by tlorusso** [comment]
We have confirmation by the TI aithorities that intubato really just includes intubated patients in the case of TI (noninvasive ventilation is excluded) @pedrodude. See #250

**Comment by pedrodude** [comment]
Many thanks!

**Comment by tlorusso** [comment]
Your welcome, thank you for bringing this up. Closing this now. @pedrodude
