### ISSUE TITLE
AI scraper didn't pick up on data from today

### ISSUE THREAD

**Issue by claudia013** [openZH/covid_19#392]

**Comment by calmyournerves** [comment]
@claudia013 Just checked the [CSV](https://github.com/openZH/covid_19/commit/8c95d8f99aee5227840fabd2560c197836e3c004) and the website ("20 laborbestätigte Fälle") and the data seems to be correct. Am I missing something?

**Comment by metaodi** [comment]
The scraper only gets one value per day, if there is already an entry for the day, nothing is changed. I'm not sure if we should change that(?).
I checked the [history of the file](https://github.com/openZH/covid_19/commits/8c95d8f99aee5227840fabd2560c197836e3c004/fallzahlen_kanton_total_csv/COVID19_Fallzahlen_Kanton_AI_total.csv), and the scraper did indeed get a value of today, but it was later corrected manually since the number changed on the website.
