### ISSUE TITLE
NE: ncumul_conf [NULL]

### ISSUE THREAD

**Issue by sandrasurber** [openZH/covid_19#427]
NE: no values for 2./3.4. in ncumul_conf, leave it empty?  [Looks ](https://rsalzer.github.io/COVID_19_CH/) like there are no cases at all

**Comment by simgraworldwide** [comment]
yes, we leave single cells empty if no data is delivered (yet) for a specific day. You see this for ncumul_conf for 2. and 3. March

**Comment by tlorusso** [comment]
@rsalzer can you handle this on your side? In your table on the top the entry for the newest date of NE is empty now:

https://rsalzer.github.io/COVID_19_CH/

This is because NE has started to report confirmed cases with some delay (in contrast to the hospitalized, which they do report daily with no delay). Maybe because they switched to 'date of test' instead of 'date of result'? Would be good to ask.

**Comment by rsalzer** [comment]
@tlorusso Corrected it. Thanks for pointing it out.

**Comment by metaodi** [comment]
related to #414
