### ISSUE TITLE
TG provides CSV via opendata.swiss

### ISSUE THREAD

**Issue by metaodi** [openZH/covid_19#493]
TG data is available here: https://opendata.swiss/de/dataset/covid_19-fallzahlen-kanton-thurgau

**Comment by baryluk** [comment]
Interesting.

https://statistik.tg.ch/public/upload/assets/94501/COVID19_Fallzahlen_Kanton_TG.csv  follows exactly our CSV format (it is using semicolons as separator).

It also has more data than us. It goes back to 2020-03-05.

However, looking at some recent values:

```csv
date;time;abbreviation_canton;ncumul_conf;ncumul_hosp;ncumul_ICU;ncumul_released;ncumul_deceased;source
...
05.04.2020;;TG;219;30;13;15;8;https://www.tg.ch/news/fachstab-gesundheit-coronavirus.html/10552
06.04.2020;;TG;228;32;13;15;8;https://www.tg.ch/news/fachstab-gesundheit-coronavirus.html/10552
07.04.2020;;TG;236;35;13;15;8;https://www.tg.ch/news/fachstab-gesundheit-coronavirus.html/10552
08.04.2020;;TG;255;35;13;15;8;https://www.tg.ch/news/fachstab-gesundheit-coronavirus.html/10552
```

But on website I see this: https://www.tg.ch/news/fachstab-gesundheit-coronavirus.html/10552

```
Aktuelle Fallzahlen im Kanton Thurgau

    Anzahl bestätigter Fälle: 255
    Hospitalisiert: 27
    davon auf der Intensivstation:  12
    Verstorben: 8

Stand 9.4.20
```


Note that hospitalized number on the website is 27, but according to csv file there were 30 since 2020-04-05 (or even 2020-04-02).

Similarly ICU numbers seems off.

https://statistik.tg.ch/public/upload/assets/94502/COVID19_Fallzahlen_Kanton_TG_Geschlecht_Alterskategorie.csv looks also good, and has extra breakdowns (age group and sex).

**Comment by baryluk** [comment]
Another plus of the CSV file, it provides information about released patients.

**Comment by metaodi** [comment]
I will check with them. Thanks for the review.

**Comment by dkoltg** [comment]
Hi, thanks for the question. The numbers in the dataset on opendata.swiss are cumulative numbers and therefore differ from the currently hospitalized patients.

**Comment by baryluk** [comment]
@dkoltg AFAIK, we don't track explicitly cumulative hospitalizations in this repo. There is `new_hosp` that can be made to track cumulative hospitalizations, but it is incremental itself. But it should be possible to calculate `new_hosp` from `ncumul_hosp` in this CSV file from TG.

**Comment by metaodi** [comment]
I asked @dkoltg to provide the CSV with the new non-cumulative fields  `current_hosp` and `new_hosp`.

**Comment by dkoltg** [comment]
I will be able to add the new_hosp numbers for the whole time after easter, sorry for the delay. The dataset is now update with columns to the current_hosp and current_icu...and newly hospitalized since the day before yesterday. Sorry for the inconvenience.

**Comment by metaodi** [comment]
@dkoltg nothing to be sorry about. Thanks for providing the CSV and Happy Easter! :rabbit:

**Comment by baryluk** [comment]
@dkoltg Thank you!

I notice, that you also left `ncumul_hosp` column, but it is empty. Would be great to actually have this data in the CSV. You had it there just hour ago.

Now it is not possible to calculate fully cumulative hospitalizations.

If it could look something like this:

```csv
06.04.2020;;TG;228;32;24;;;12;25;8;https://www.tg.ch/news/fachstab-gesundheit-coronavirus.html/10552;;;;;;
07.04.2020;;TG;248;35;27;3;;12;25;8;https://www.tg.ch/news/fachstab-gesundheit-coronavirus.html/10552;;;;;;
08.04.2020;;TG;255;35;27;0;;12;25;8;https://www.tg.ch/news/fachstab-gesundheit-coronavirus.html/10552;;;;;;
```

that would make it a bit better.

I also noticed that values for ICU changed. So it now looks it is not possible to get fully cumulative ICU numbers either?

The fact that we don't track this numbers in this repo (yet), doesn't mean we don't want them to be provided. It would be great to have them!

**Comment by dkoltg** [comment]
Hi @baryluk 
Thanks to your question, I discovered some mistakes in the dataset. I updated it just now, without columns for cumulative numbers for hospitalisation and icu as I don't have the data at the moment. I will try to add all numbers for new hospitalisations and - if possible - also for new icu-cases for the whole period. However, that won't be before easter. Thanks for your patience.

**Comment by baryluk** [comment]
@dkoltg 

Thanks for the clarification. No worries at all. We will revisit after Easter then.

**Comment by dkoltg** [comment]
@baryluk 
Thanks for your help to improve the dataset! Happy easter :)

**Comment by dkoltg** [comment]
Hi, I had to modify the TG-dataset because there were some differences between the numbers the Gesundheitsamt published and the dataset on opendata.swiss. I will fill up the missing cells for current_hosp, current_icu and new_hosp after easter as soon as I will have received all the necessary data from the correspondent person.

**Comment by baryluk** [comment]
@dkoltg Thank you. `new_hosp` or `cumul_hosp` (total real cumulative since the start) are both find for us. I personally prefer the cumulative, but any way should be fine.

Do you know how often your dataset on opendata.swiss / github, is going to be updated? If it is going to be back and forth everyday, between you and others, I am not sure how sustainable it is. If you could ask them to send the data regularly by email, that could work I guess. What do you think?

Have a good day.

**Comment by dkoltg** [comment]
@baryluk Hi, I am not sure I understand your question. I update our dataset everyday before noon with the number that are reported by our heath office around 10 am. The first dataset I got was the one from 4/9 and I hope to get the older datasets soon, so that I can fill the empty cells for new_hosp. As I try to update the data in the same way every day (apart from the first struggles I had with them as the topic was completly new for me), I guess the results should be sustainable. Or what do you mean?
Best wishes,

**Comment by baryluk** [comment]
> @baryluk Hi, I am not sure I understand your question. I update our dataset everyday before noon with the number that are reported by our heath office around 10 am. The first dataset I got was the one from 4/9 and I hope to get the older datasets soon, so that I can fill the empty cells for new_hosp. As I try to update the data in the same way every day (apart from the first struggles I had with them as the topic was completly new for me), I guess the results should be sustainable. Or what do you mean?
> Best wishes,

Yes, that sounds great. I was just checking.

**Comment by metaodi** [comment]
@baryluk are you planning to work on this? Or is this up for grabs?

**Comment by metaodi** [comment]
This is currently not needed as TG will start to update this repo directly. For now the current scraper acts as a fallback.
