### ISSUE TITLE
Drop in hospitalization numbers

### ISSUE THREAD

**Issue by Melandra** [openZH/covid_19#659]
@simgraworldwide: as requested I let you know that I've noticed a drop in the hospitalization numbers, the same pattern as last time. I made a few screenshots, maybe they help to get insights into what is happening...
![Screenshot_20200503-122708_SRF](https://user-images.githubusercontent.com/17590748/80912029-6deba200-8d3a-11ea-813c-806e959d0b70.jpg)
![Screenshot_20200503-122703_SRF](https://user-images.githubusercontent.com/17590748/80912037-73e18300-8d3a-11ea-86bd-0294d3cf6939.jpg)
![Screenshot_20200503-122657_SRF](https://user-images.githubusercontent.com/17590748/80912042-793ecd80-8d3a-11ea-9184-d0ba5fb7dbc3.jpg)
![Screenshot_20200503-122653_SRF](https://user-images.githubusercontent.com/17590748/80912049-7fcd4500-8d3a-11ea-91e5-6ff1dbcf510c.jpg)

**Comment by simgraworldwide** [comment]
I am sorry, I still don't seem to fully understand. If your question is, why the overall numbers of hospitalisations and ICUs are decreasing, that is because these numbers are not cumulated, as stated in our README file (https://github.com/openZH/covid_19/blob/master/README.md).
If that is not what you mean, may I ask you to give me a quick call at +41 43 259 75 38?

**Comment by simgraworldwide** [comment]
Ok @Melandra , we found the problem. The script for the graph filters all cantons, that either publish only hospitalised but not ICUs (this will remain) and, furthermore, all cantons that have not published hospitalised data in the last three days. The entire time series data is filtered for these cantons to gain consistency.
Several cantons do publish data on hospitalisations for the weekend days only retrospectively on Monday. With 1st of May being a Friday, some passed this three day threshold, removing their data from the graph entirely.
The script will be adjusted, so that a canton has to not publish data on hospitalisations for more than three days until they are removed from the graph.
Thanks again for letting us know!

**Comment by grssnbchr** [comment]
As Simon says, we will adapt our script slightly so that the likelihood a canton is fully removed from the chart for some period of time is reduced. Thanks for bringing this to our attention.
Timo (SRF Data)
