### ISSUE TITLE
Stale data for several cantons in COVID19_Fallzahlen_CH_total_v2.csv

### ISSUE THREAD

**Issue by jeffpires** [openZH/covid_19#932]
Geneva data is now a full week behind, with several other cantons also falling stale.  The Geneva [source](https://www.ge.ch/document/20094/annexe/0) in particular appears to have stopped providing updates.  Perhaps the BAG "Data from the situation report" xls files [here](https://www.bag.admin.ch/bag/en/home/krankheiten/ausbrueche-epidemien-pandemien/aktuelle-ausbrueche-epidemien/novel-cov/situation-schweiz-und-international.html) may be a suitable replacement?

GE | 2020-07-20
NE | 2020-07-22
VD | 2020-07-22
NW | 2020-07-24
OW | 2020-07-24
JU | 2020-07-24
VS | 2020-07-24
TG | 2020-07-24
GL | 2020-07-24
UR | 2020-07-24
AR | 2020-07-24
BL | 2020-07-24

**Comment by metaodi** [comment]
I agree, that many cantons have a certain lag, and do not provide daily updates, they still publish data on a regular basis. GE even announced to switch to daily updates since this issue has been created.

The idea of this repository is to make the data published by the cantons available in a machine-readble format. But as [communicated before](https://github.com/openZH/covid_19/issues/909#issuecomment-659331843), we want to stick to the principle, to not mix cantonal data with BAG data.
